name: Create new day
on: 
  schedule:
    - cron:  '0 1 * * *'

jobs:
  create-new-day:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/create-new-day.js')
            script(github, context, exec)